/* Generated by tools/build-generic-math-map-assets.mjs. Do not edit. */
window.CMATH_GENERIC_MAP_REGISTRY = Object.freeze({
  "schema": "cmath-gamma.generic-math-map-runtime-registry/v0.1",
  "maps": [
    {
      "id": "group-theory",
      "title": "群、陪集与 Lagrange 定理",
      "projectId": "cmath:project:group-theory-content-example",
      "workspaceViews": [
        "global"
      ],
      "mathTextFormat": "cmath-gamma.math-text/legacy-compatible-v0",
      "contentAdmissionProfile": "legacy-unreviewed-v0",
      "contentFingerprint": null,
      "dataScript": "generated-math-content/group-theory-project-data.js",
      "boundaryLabel": "一般数学内容 · Gamma-native 只读地图"
    },
    {
      "id": "spectral-theorem",
      "title": "从特征值到谱定理",
      "projectId": "cmath:project:spectral-theorem",
      "workspaceViews": [
        "global",
        "progress"
      ],
      "mathTextFormat": "cmath-gamma.math-text/latex-delimited-v1",
      "contentAdmissionProfile": "mature-mathematics-lightweight-v1",
      "contentFingerprint": "fnv1a32:b92b9931",
      "dataScript": "generated-math-content/spectral-theorem-project-data.js",
      "boundaryLabel": "高等代数示例 · 数学地图与 Loop 进展"
    },
    {
      "id": "intermediate-value-theorem",
      "title": "从闭区间套到介值定理",
      "projectId": "cmath:project:intermediate-value-theorem",
      "workspaceViews": [
        "global",
        "progress"
      ],
      "mathTextFormat": "cmath-gamma.math-text/latex-delimited-v1",
      "contentAdmissionProfile": "mature-mathematics-lightweight-v1",
      "contentFingerprint": "fnv1a32:803c8c8e",
      "dataScript": "generated-math-content/intermediate-value-theorem-project-data.js",
      "boundaryLabel": "数学分析示例 · 数学地图与 Loop 进展"
    },
    {
      "id": "fundamental-theorem-calculus",
      "title": "从积分累积函数到微积分基本定理",
      "projectId": "cmath:project:fundamental-theorem-calculus",
      "workspaceViews": [
        "global",
        "progress"
      ],
      "mathTextFormat": "cmath-gamma.math-text/latex-delimited-v1",
      "contentAdmissionProfile": "mature-mathematics-lightweight-v1",
      "contentFingerprint": "fnv1a32:bee65a3f",
      "dataScript": "generated-math-content/fundamental-theorem-calculus-project-data.js",
      "boundaryLabel": "微积分示例 · 数学地图与 Loop 进展"
    },
    {
      "id": "three-manifolds-finite-covers",
      "title": "三维流形中的曲面、有限覆盖与可分性",
      "projectId": "cmath:project:three-manifolds-finite-covers",
      "workspaceViews": [
        "global"
      ],
      "mathTextFormat": "cmath-gamma.math-text/legacy-compatible-v0",
      "contentAdmissionProfile": "legacy-unreviewed-v0",
      "contentFingerprint": null,
      "dataScript": "generated-math-content/three-manifolds-finite-covers-project-data.js",
      "boundaryLabel": "以三维流形中的嵌入曲面为主线，群、图与立方复形作为有限覆盖工具"
    },
    {
      "id": "three-manifolds-topological-finite-cover",
      "title": "三维流形中的曲面与有限覆盖",
      "projectId": "cmath:project:three-manifolds-topological-finite-cover",
      "workspaceViews": [
        "global"
      ],
      "mathTextFormat": "cmath-gamma.math-text/legacy-compatible-v0",
      "contentAdmissionProfile": "legacy-unreviewed-v0",
      "contentFingerprint": null,
      "dataScript": "generated-math-content/three-manifolds-topological-finite-cover-project-data.js",
      "boundaryLabel": "以三维流形中的不可压缩曲面和 virtually Haken 为主线"
    },
    {
      "id": "jsj-decomposition",
      "title": "JSJ 分解、Seifert 块与双曲块",
      "projectId": "cmath:project:jsj-decomposition",
      "workspaceViews": [
        "global"
      ],
      "mathTextFormat": "cmath-gamma.math-text/latex-delimited-v1",
      "contentAdmissionProfile": "mature-mathematics-lightweight-v1",
      "contentFingerprint": "fnv1a32:c67f75ca",
      "dataScript": "generated-math-content/jsj-decomposition-project-data.js",
      "boundaryLabel": "一般数学内容 · Gamma-native 只读地图"
    }
  ]
});
