import { readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(here, "..");
const RELEASE_META_NAME = "cmath-production-release";
const RUNTIME_START = "<!-- CMATH_PRODUCTION_RUNTIME_START -->";
const RUNTIME_END = "<!-- CMATH_PRODUCTION_RUNTIME_END -->";

function freezeScript(src, { versioned = true } = {}) {
  return Object.freeze({ src, versioned });
}

const PRODUCTION_RELEASE_ID = "20260830-v51-release-2";
const PRODUCTION_RUNTIME_SCRIPTS = Object.freeze([
  freezeScript("portable-maps-data.js"),
  freezeScript("vendor/force-graph/force-graph.min.js", { versioned: false }),
  freezeScript("vendor/katex/katex.min.js", { versioned: false }),
  freezeScript("vendor/fflate/fflate.min.js", { versioned: false }),
  freezeScript("math-text.js"),
  freezeScript("math-rendering-consumer.js"),
  freezeScript("graph-contract.js"),
  freezeScript("graph-canvas.js"),
  freezeScript("capabilities/runtime/packages/math-map/state/math-graph-semantics-v3/src/index.js"),
  freezeScript("math-map-semantics-v3-bridge.js"),
  freezeScript("math-map-semantics.js"),
  freezeScript("math-map-naming.js"),
  freezeScript("research-loop-progress.js"),
  freezeScript("math-map-visual-semantics.js"),
  freezeScript("math-map-content-loader.js"),
  freezeScript("generic-math-map-preview-loader.js"),
  freezeScript("math-map-project-adapter.js"),
  freezeScript("canonical-math-map-adapter.js"),
  freezeScript("generated-math-content/registry.js"),
  freezeScript("paper-import-v3-capability.js"),
  freezeScript("guide-lead-contract-v1.js"),
  freezeScript("lead-guided-extraction-v1.js"),
  freezeScript("dual-lane-extraction-aggregation-v1.js"),
  freezeScript("src/paper-import/core/validation.js"),
  freezeScript("src/paper-import/core/project-view.js"),
  freezeScript("src/paper-import/core/model-transport.js"),
  freezeScript("paper-raw-entry-pool-v1.js"),
  freezeScript("src/paper-import/entry/artifact.js"),
  freezeScript("paper-entry-artifact-v1.js"),
  freezeScript("src/paper-import/entry/lifecycle.js"),
  freezeScript("src/paper-import/entry/consolidation.js"),
  freezeScript("src/paper-import/entry/verification.js"),
  freezeScript("src/paper-import/entry/index.js"),
  freezeScript("src/paper-import/inference/strategies/v3.43.js"),
  freezeScript("src/paper-import/inference/strategies/v3.44.js"),
  freezeScript("src/paper-import/inference/strategies/v3.45.js"),
  freezeScript("src/paper-import/inference/strategies/index.js"),
  freezeScript("src/paper-import/inference/lifecycle.js"),
  freezeScript("src/paper-import/inference/index.js"),
  freezeScript("src/paper-import/mineru/marked-markdown.js"),
  freezeScript("src/paper-import/mineru/client.js"),
  freezeScript("src/paper-import/mineru/index.js"),
  freezeScript("src/paper-import/workflow/checkpoint-store.js"),
  freezeScript("src/map-library/core.js"),
  freezeScript("src/paper-import/workflow/production.js"),
  freezeScript("src/paper-import/workflow/index.js"),
  freezeScript("src/paper-import/canonical/v5.js"),
  freezeScript("src/paper-import/production/index.js"),
  freezeScript("paper-import-client.js"),
  freezeScript("app-v5.js"),
]);

export const PRODUCTION_RELEASE = Object.freeze({
  id: PRODUCTION_RELEASE_ID,
  scriptCount: PRODUCTION_RUNTIME_SCRIPTS.length,
});

function scriptSource(script) {
  return script.versioned ? `${script.src}?v=${PRODUCTION_RELEASE.id}` : script.src;
}

export function productionAssetSource(src) {
  const script = PRODUCTION_RUNTIME_SCRIPTS.find((candidate) => candidate.src === src);
  if (!script) throw new Error(`资源不属于当前生产发布：${src}`);
  return scriptSource(script);
}

function runtimeMarkup() {
  const tags = PRODUCTION_RUNTIME_SCRIPTS
    .map((script) => `  <script src="${scriptSource(script)}"></script>`)
    .join("\n");
  return `  <!-- Runtime Scripts: generated by scripts/production-release.mjs -->\n  ${RUNTIME_START}\n${tags}\n  ${RUNTIME_END}`;
}

function withReleaseMeta(html) {
  const meta = `<meta name="${RELEASE_META_NAME}" content="${PRODUCTION_RELEASE.id}" />`;
  const existing = new RegExp(`<meta\\s+name=["']${RELEASE_META_NAME}["'][^>]*>`, "u");
  if (existing.test(html)) return html.replace(existing, meta);
  const viewport = /(<meta\s+name=["']viewport["'][^>]*>)/u;
  if (!viewport.test(html)) throw new Error("生产入口缺少 viewport meta，无法写入发布身份");
  return html.replace(viewport, `$1\n  ${meta}`);
}

export function renderProductionEntryHtml(sourceHtml) {
  const html = withReleaseMeta(String(sourceHtml));
  const generatedBlock = new RegExp(
    `  <!-- Runtime Scripts: generated by scripts/production-release\\.mjs -->\\n  ${RUNTIME_START}[\\s\\S]*?  ${RUNTIME_END}`,
    "u",
  );
  if (generatedBlock.test(html)) return html.replace(generatedBlock, runtimeMarkup());

  const legacyBlock = /  <!-- Runtime Scripts -->[\s\S]*?(?=\n<\/body>)/u;
  if (!legacyBlock.test(html)) throw new Error("生产入口缺少 Runtime Scripts 区块");
  return html.replace(legacyBlock, runtimeMarkup());
}

function releaseIdOf(html) {
  const match = String(html).match(new RegExp(`<meta\\s+name=["']${RELEASE_META_NAME}["']\\s+content=["']([^"']+)["']\\s*\\/?\\s*>`, "u"));
  return match?.[1] ?? null;
}

function scriptSourcesOf(html) {
  return [...String(html).matchAll(/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gu)]
    .map((match) => match[1]);
}

export function inspectProductionEntries({ canonicalHtml, mirrorHtml }) {
  const canonical = String(canonicalHtml);
  const mirror = String(mirrorHtml);
  if (mirror !== canonical) throw new Error("index-v5.html 不是 index.html 的当前生成镜像");
  const releaseId = releaseIdOf(canonical);
  if (releaseId !== PRODUCTION_RELEASE.id) {
    throw new Error(`生产入口发布身份不匹配：期望 ${PRODUCTION_RELEASE.id}，实际 ${releaseId ?? "缺失"}`);
  }
  const actualSources = scriptSourcesOf(canonical);
  const expectedSources = PRODUCTION_RUNTIME_SCRIPTS.map(scriptSource);
  if (actualSources.length !== expectedSources.length
    || actualSources.some((source, index) => source !== expectedSources[index])) {
    throw new Error("生产入口脚本与发布清单不一致，请运行 npm run sync:production-entry");
  }
  return Object.freeze({ releaseId, scriptCount: actualSources.length });
}

async function atomicWrite(target, content) {
  const temporary = `${target}.${process.pid}.tmp`;
  await writeFile(temporary, content, "utf8");
  await rename(temporary, target);
}

export async function syncProductionEntries({ root = repositoryRoot, check = false } = {}) {
  const canonicalPath = resolve(root, "index.html");
  const mirrorPath = resolve(root, "index-v5.html");
  const canonicalSource = await readFile(canonicalPath, "utf8");
  const canonicalHtml = renderProductionEntryHtml(canonicalSource);
  const mirrorHtml = canonicalHtml;

  if (check) {
    const committedMirror = await readFile(mirrorPath, "utf8");
    inspectProductionEntries({ canonicalHtml: canonicalSource, mirrorHtml: committedMirror });
    return Object.freeze({ releaseId: PRODUCTION_RELEASE.id, changed: false });
  }

  await atomicWrite(canonicalPath, canonicalHtml);
  await atomicWrite(mirrorPath, mirrorHtml);
  return Object.freeze({ releaseId: PRODUCTION_RELEASE.id, changed: canonicalSource !== canonicalHtml });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const check = process.argv.includes("--check");
  try {
    const result = await syncProductionEntries({ check });
    console.log(check
      ? `生产入口校验通过：${result.releaseId}`
      : `生产入口已同步：${result.releaseId}`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
